// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: proto/track_order.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrackOrderService_UpdateStatus_FullMethodName    = "/track_order.TrackOrderService/UpdateStatus"
	TrackOrderService_GetTrackingInfo_FullMethodName = "/track_order.TrackOrderService/GetTrackingInfo"
)

// TrackOrderServiceClient is the client API for TrackOrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrackOrderServiceClient interface {
	UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*TrackOrderResponse, error)
	GetTrackingInfo(ctx context.Context, in *GetTrackingInfoRequest, opts ...grpc.CallOption) (*TrackOrderResponse, error)
}

type trackOrderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrackOrderServiceClient(cc grpc.ClientConnInterface) TrackOrderServiceClient {
	return &trackOrderServiceClient{cc}
}

func (c *trackOrderServiceClient) UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*TrackOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackOrderResponse)
	err := c.cc.Invoke(ctx, TrackOrderService_UpdateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackOrderServiceClient) GetTrackingInfo(ctx context.Context, in *GetTrackingInfoRequest, opts ...grpc.CallOption) (*TrackOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackOrderResponse)
	err := c.cc.Invoke(ctx, TrackOrderService_GetTrackingInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrackOrderServiceServer is the server API for TrackOrderService service.
// All implementations must embed UnimplementedTrackOrderServiceServer
// for forward compatibility.
type TrackOrderServiceServer interface {
	UpdateStatus(context.Context, *UpdateStatusRequest) (*TrackOrderResponse, error)
	GetTrackingInfo(context.Context, *GetTrackingInfoRequest) (*TrackOrderResponse, error)
	mustEmbedUnimplementedTrackOrderServiceServer()
}

// UnimplementedTrackOrderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrackOrderServiceServer struct{}

func (UnimplementedTrackOrderServiceServer) UpdateStatus(context.Context, *UpdateStatusRequest) (*TrackOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (UnimplementedTrackOrderServiceServer) GetTrackingInfo(context.Context, *GetTrackingInfoRequest) (*TrackOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrackingInfo not implemented")
}
func (UnimplementedTrackOrderServiceServer) mustEmbedUnimplementedTrackOrderServiceServer() {}
func (UnimplementedTrackOrderServiceServer) testEmbeddedByValue()                           {}

// UnsafeTrackOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrackOrderServiceServer will
// result in compilation errors.
type UnsafeTrackOrderServiceServer interface {
	mustEmbedUnimplementedTrackOrderServiceServer()
}

func RegisterTrackOrderServiceServer(s grpc.ServiceRegistrar, srv TrackOrderServiceServer) {
	// If the following call panics, it indicates UnimplementedTrackOrderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrackOrderService_ServiceDesc, srv)
}

func _TrackOrderService_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackOrderServiceServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackOrderService_UpdateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackOrderServiceServer).UpdateStatus(ctx, req.(*UpdateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackOrderService_GetTrackingInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackingInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackOrderServiceServer).GetTrackingInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackOrderService_GetTrackingInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackOrderServiceServer).GetTrackingInfo(ctx, req.(*GetTrackingInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrackOrderService_ServiceDesc is the grpc.ServiceDesc for TrackOrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrackOrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "track_order.TrackOrderService",
	HandlerType: (*TrackOrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateStatus",
			Handler:    _TrackOrderService_UpdateStatus_Handler,
		},
		{
			MethodName: "GetTrackingInfo",
			Handler:    _TrackOrderService_GetTrackingInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/track_order.proto",
}
