// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/track_order.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrackOrder struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId        string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ShippingStatus string                 `protobuf:"bytes,3,opt,name=shipping_status,json=shippingStatus,proto3" json:"shipping_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrackOrder) Reset() {
	*x = TrackOrder{}
	mi := &file_proto_track_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackOrder) ProtoMessage() {}

func (x *TrackOrder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_track_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackOrder.ProtoReflect.Descriptor instead.
func (*TrackOrder) Descriptor() ([]byte, []int) {
	return file_proto_track_order_proto_rawDescGZIP(), []int{0}
}

func (x *TrackOrder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TrackOrder) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *TrackOrder) GetShippingStatus() string {
	if x != nil {
		return x.ShippingStatus
	}
	return ""
}

type UpdateStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ShippingStatus string                 `protobuf:"bytes,2,opt,name=shipping_status,json=shippingStatus,proto3" json:"shipping_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_proto_track_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_track_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_track_order_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateStatusRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateStatusRequest) GetShippingStatus() string {
	if x != nil {
		return x.ShippingStatus
	}
	return ""
}

type GetTrackingInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackingInfoRequest) Reset() {
	*x = GetTrackingInfoRequest{}
	mi := &file_proto_track_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackingInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackingInfoRequest) ProtoMessage() {}

func (x *GetTrackingInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_track_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackingInfoRequest.ProtoReflect.Descriptor instead.
func (*GetTrackingInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_track_order_proto_rawDescGZIP(), []int{2}
}

func (x *GetTrackingInfoRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type TrackOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackOrder    *TrackOrder            `protobuf:"bytes,1,opt,name=track_order,json=trackOrder,proto3" json:"track_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackOrderResponse) Reset() {
	*x = TrackOrderResponse{}
	mi := &file_proto_track_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackOrderResponse) ProtoMessage() {}

func (x *TrackOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_track_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackOrderResponse.ProtoReflect.Descriptor instead.
func (*TrackOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_track_order_proto_rawDescGZIP(), []int{3}
}

func (x *TrackOrderResponse) GetTrackOrder() *TrackOrder {
	if x != nil {
		return x.TrackOrder
	}
	return nil
}

var File_proto_track_order_proto protoreflect.FileDescriptor

const file_proto_track_order_proto_rawDesc = "" +
	"\n" +
	"\x17proto/track_order.proto\x12\vtrack_order\"`\n" +
	"\n" +
	"TrackOrder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12'\n" +
	"\x0fshipping_status\x18\x03 \x01(\tR\x0eshippingStatus\"Y\n" +
	"\x13UpdateStatusRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12'\n" +
	"\x0fshipping_status\x18\x02 \x01(\tR\x0eshippingStatus\"3\n" +
	"\x16GetTrackingInfoRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"N\n" +
	"\x12TrackOrderResponse\x128\n" +
	"\vtrack_order\x18\x01 \x01(\v2\x17.track_order.TrackOrderR\n" +
	"trackOrder2\xbf\x01\n" +
	"\x11TrackOrderService\x12Q\n" +
	"\fUpdateStatus\x12 .track_order.UpdateStatusRequest\x1a\x1f.track_order.TrackOrderResponse\x12W\n" +
	"\x0fGetTrackingInfo\x12#.track_order.GetTrackingInfoRequest\x1a\x1f.track_order.TrackOrderResponseB\x1bZ\x19track-order-service/protob\x06proto3"

var (
	file_proto_track_order_proto_rawDescOnce sync.Once
	file_proto_track_order_proto_rawDescData []byte
)

func file_proto_track_order_proto_rawDescGZIP() []byte {
	file_proto_track_order_proto_rawDescOnce.Do(func() {
		file_proto_track_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_track_order_proto_rawDesc), len(file_proto_track_order_proto_rawDesc)))
	})
	return file_proto_track_order_proto_rawDescData
}

var file_proto_track_order_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_track_order_proto_goTypes = []any{
	(*TrackOrder)(nil),             // 0: track_order.TrackOrder
	(*UpdateStatusRequest)(nil),    // 1: track_order.UpdateStatusRequest
	(*GetTrackingInfoRequest)(nil), // 2: track_order.GetTrackingInfoRequest
	(*TrackOrderResponse)(nil),     // 3: track_order.TrackOrderResponse
}
var file_proto_track_order_proto_depIdxs = []int32{
	0, // 0: track_order.TrackOrderResponse.track_order:type_name -> track_order.TrackOrder
	1, // 1: track_order.TrackOrderService.UpdateStatus:input_type -> track_order.UpdateStatusRequest
	2, // 2: track_order.TrackOrderService.GetTrackingInfo:input_type -> track_order.GetTrackingInfoRequest
	3, // 3: track_order.TrackOrderService.UpdateStatus:output_type -> track_order.TrackOrderResponse
	3, // 4: track_order.TrackOrderService.GetTrackingInfo:output_type -> track_order.TrackOrderResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_track_order_proto_init() }
func file_proto_track_order_proto_init() {
	if File_proto_track_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_track_order_proto_rawDesc), len(file_proto_track_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_track_order_proto_goTypes,
		DependencyIndexes: file_proto_track_order_proto_depIdxs,
		MessageInfos:      file_proto_track_order_proto_msgTypes,
	}.Build()
	File_proto_track_order_proto = out.File
	file_proto_track_order_proto_goTypes = nil
	file_proto_track_order_proto_depIdxs = nil
}
