package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"api-gateway/graph/model"
	"context"
	"fmt"

	orderpb "order-service/proto"
	trackorderpb "track-order-service/proto"
	userpb "user-service/proto"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, userID string, itemName string, quantity int, totalPrice float64) (*model.Order, error) {
	// Verify user exists first
	_, err := r.UserClient.GetUser(ctx, &userpb.GetUserRequest{Id: userID})
	if err != nil {
		return nil, fmt.Errorf("cannot create order: user not found: %v", err)
	}

	resp, err := r.OrderClient.CreateOrder(ctx, &orderpb.CreateOrderRequest{
		UserId:     userID,
		ItemName:   itemName,
		Quantity:   int32(quantity),
		TotalPrice: float32(totalPrice),
	})
	if err != nil {
		return nil, err
	}
	return &model.Order{
		ID:         resp.Order.Id,
		UserID:     resp.Order.UserId,
		ItemName:   resp.Order.ItemName,
		Quantity:   int(resp.Order.Quantity),
		TotalPrice: float64(resp.Order.TotalPrice),
		Status:     resp.Order.Status,
	}, nil
}

// UpdateTrackingStatus is the resolver for the updateTrackingStatus field.
func (r *mutationResolver) UpdateTrackingStatus(ctx context.Context, orderID string, shippingStatus string) (*model.TrackOrder, error) {
	// Verify order exists first
	_, err := r.OrderClient.GetOrder(ctx, &orderpb.GetOrderRequest{Id: orderID})
	if err != nil {
		return nil, fmt.Errorf("cannot update tracking: order not found: %v", err)
	}

	resp, err := r.TrackOrderClient.UpdateStatus(ctx, &trackorderpb.UpdateStatusRequest{
		OrderId:        orderID,
		ShippingStatus: shippingStatus,
	})
	if err != nil {
		return nil, err
	}
	return &model.TrackOrder{
		ID:             resp.TrackOrder.Id,
		OrderID:        resp.TrackOrder.OrderId,
		ShippingStatus: resp.TrackOrder.ShippingStatus,
	}, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, username string, email string) (*model.User, error) {
	resp, err := r.UserClient.CreateUser(ctx, &userpb.CreateUserRequest{
		Username: username,
		Email:    email,
	})
	if err != nil {
		return nil, err
	}
	return &model.User{
		ID:       resp.User.Id,
		Username: resp.User.Username,
		Email:    resp.User.Email,
	}, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, username string, email string) (*model.User, error) {
	resp, err := r.UserClient.UpdateUser(ctx, &userpb.UpdateUserRequest{
		Id:       id,
		Username: username,
		Email:    email,
	})
	if err != nil {
		return nil, err
	}
	return &model.User{
		ID:       resp.User.Id,
		Username: resp.User.Username,
		Email:    resp.User.Email,
	}, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	resp, err := r.UserClient.DeleteUser(ctx, &userpb.DeleteUserRequest{Id: id})
	if err != nil {
		return false, err
	}
	return resp.Success, nil
}

// GetOrder is the resolver for the getOrder field.
func (r *queryResolver) GetOrder(ctx context.Context, id string) (*model.Order, error) {
	resp, err := r.OrderClient.GetOrder(ctx, &orderpb.GetOrderRequest{Id: id})
	if err != nil {
		return nil, err
	}
	return &model.Order{
		ID:         resp.Order.Id,
		UserID:     resp.Order.UserId,
		ItemName:   resp.Order.ItemName,
		Quantity:   int(resp.Order.Quantity),
		TotalPrice: float64(resp.Order.TotalPrice),
		Status:     resp.Order.Status,
	}, nil
}

// ListOrders is the resolver for the listOrders field.
func (r *queryResolver) ListOrders(ctx context.Context) ([]*model.Order, error) {
	resp, err := r.OrderClient.ListOrders(ctx, &orderpb.ListOrdersRequest{})
	if err != nil {
		return nil, err
	}
	var orders []*model.Order
	for _, order := range resp.Orders {
		orders = append(orders, &model.Order{
			ID:         order.Id,
			UserID:     order.UserId,
			ItemName:   order.ItemName,
			Quantity:   int(order.Quantity),
			TotalPrice: float64(order.TotalPrice),
			Status:     order.Status,
		})
	}
	return orders, nil
}

// GetTrackingInfo is the resolver for the getTrackingInfo field.
func (r *queryResolver) GetTrackingInfo(ctx context.Context, orderID string) (*model.TrackOrder, error) {
	resp, err := r.TrackOrderClient.GetTrackingInfo(ctx, &trackorderpb.GetTrackingInfoRequest{OrderId: orderID})
	if err != nil {
		return nil, err
	}
	return &model.TrackOrder{
		ID:             resp.TrackOrder.Id,
		OrderID:        resp.TrackOrder.OrderId,
		ShippingStatus: resp.TrackOrder.ShippingStatus,
	}, nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*model.User, error) {
	resp, err := r.UserClient.GetUser(ctx, &userpb.GetUserRequest{Id: id})
	if err != nil {
		return nil, err
	}
	return &model.User{
		ID:       resp.User.Id,
		Username: resp.User.Username,
		Email:    resp.User.Email,
	}, nil
}

// ListUsers is the resolver for the listUsers field.
func (r *queryResolver) ListUsers(ctx context.Context) ([]*model.User, error) {
	resp, err := r.UserClient.ListUsers(ctx, &userpb.ListUsersRequest{})
	if err != nil {
		return nil, err
	}
	var users []*model.User
	for _, user := range resp.Users {
		users = append(users, &model.User{
			ID:       user.Id,
			Username: user.Username,
			Email:    user.Email,
		})
	}
	return users, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
