type Order {
  id: ID!
  user_id: String!
  item_name: String!
  quantity: Int!
  total_price: Float!
  status: String!
}

type TrackOrder {
  id: ID!
  order_id: String!
  shipping_status: String!
}

type User {
  id: ID!
  username: String!
  email: String!
}

type Query {
  getOrder(id: ID!): Order!
  listOrders: [Order!]!
  getTrackingInfo(order_id: String!): TrackOrder!
  getUser(id: ID!): User!
  listUsers: [User!]!
}

type Mutation {
  createOrder(user_id: String!, item_name: String!, quantity: Int!, total_price: Float!): Order!
  updateTrackingStatus(order_id: String!, shipping_status: String!): TrackOrder!
  createUser(username: String!, email: String!): User!
  updateUser(id: ID!, username: String!, email: String!): User!
  deleteUser(id: ID!): Boolean!
}
