package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"api-gateway/graph/model"
	"context"
	pb "task-service/proto"
	userpb "user-service/proto"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, title string, description string) (*model.Task, error) {
	resp, err := r.TaskClient.CreateTask(ctx, &pb.CreateTaskRequest{
		Title:       title,
		Description: description,
	})
	if err != nil {
		return nil, err
	}
	return &model.Task{
		ID:          resp.Task.Id,
		Title:       resp.Task.Title,
		Description: resp.Task.Description,
		Completed:   resp.Task.Completed,
	}, nil
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id string, title string, description string, completed bool) (*model.Task, error) {
	resp, err := r.TaskClient.UpdateTask(ctx, &pb.UpdateTaskRequest{
		Id:          id,
		Title:       title,
		Description: description,
		Completed:   completed,
	})
	if err != nil {
		return nil, err
	}
	return &model.Task{
		ID:          resp.Task.Id,
		Title:       resp.Task.Title,
		Description: resp.Task.Description,
		Completed:   resp.Task.Completed,
	}, nil
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (bool, error) {
	resp, err := r.TaskClient.DeleteTask(ctx, &pb.DeleteTaskRequest{Id: id})
	if err != nil {
		return false, err
	}
	return resp.Success, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, username string, email string) (*model.User, error) {
	resp, err := r.UserClient.CreateUser(ctx, &userpb.CreateUserRequest{
		Username: username,
		Email:    email,
	})
	if err != nil {
		return nil, err
	}
	return &model.User{
		ID:       resp.User.Id,
		Username: resp.User.Username,
		Email:    resp.User.Email,
	}, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, username string, email string) (*model.User, error) {
	resp, err := r.UserClient.UpdateUser(ctx, &userpb.UpdateUserRequest{
		Id:       id,
		Username: username,
		Email:    email,
	})
	if err != nil {
		return nil, err
	}
	return &model.User{
		ID:       resp.User.Id,
		Username: resp.User.Username,
		Email:    resp.User.Email,
	}, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	resp, err := r.UserClient.DeleteUser(ctx, &userpb.DeleteUserRequest{Id: id})
	if err != nil {
		return false, err
	}
	return resp.Success, nil
}

// GetTask is the resolver for the getTask field.
func (r *queryResolver) GetTask(ctx context.Context, id string) (*model.Task, error) {
	resp, err := r.TaskClient.GetTask(ctx, &pb.GetTaskRequest{Id: id})
	if err != nil {
		return nil, err
	}
	return &model.Task{
		ID:          resp.Task.Id,
		Title:       resp.Task.Title,
		Description: resp.Task.Description,
		Completed:   resp.Task.Completed,
	}, nil
}

// ListTasks is the resolver for the listTasks field.
func (r *queryResolver) ListTasks(ctx context.Context) ([]*model.Task, error) {
	resp, err := r.TaskClient.ListTasks(ctx, &pb.ListTasksRequest{})
	if err != nil {
		return nil, err
	}
	var tasks []*model.Task
	for _, task := range resp.Tasks {
		tasks = append(tasks, &model.Task{
			ID:          task.Id,
			Title:       task.Title,
			Description: task.Description,
			Completed:   task.Completed,
		})
	}
	return tasks, nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*model.User, error) {
	resp, err := r.UserClient.GetUser(ctx, &userpb.GetUserRequest{Id: id})
	if err != nil {
		return nil, err
	}
	return &model.User{
		ID:       resp.User.Id,
		Username: resp.User.Username,
		Email:    resp.User.Email,
	}, nil
}

// ListUsers is the resolver for the listUsers field.
func (r *queryResolver) ListUsers(ctx context.Context) ([]*model.User, error) {
	resp, err := r.UserClient.ListUsers(ctx, &userpb.ListUsersRequest{})
	if err != nil {
		return nil, err
	}
	var users []*model.User
	for _, user := range resp.Users {
		users = append(users, &model.User{
			ID:       user.Id,
			Username: user.Username,
			Email:    user.Email,
		})
	}
	return users, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
